// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using Web.App.Models;

namespace Web.App.Migrations
{
    [DbContext(typeof(CustomConnectionContext))]
    [Migration("20180205123006_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Web.App.Models.CustomConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Host");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Port");

                    b.Property<string>("SID");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("CustomConnection");
                });

            modelBuilder.Entity("Web.App.Models.TableMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SequenceName");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.ToTable("TableMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
